library:
  source-dirs: src
tests:
  hs-learn-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-learn
copyright: MIT
maintainer: kubukoz@gmail.com
dependencies:
- base >= 4.7 && < 5
name: hs-learn
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Jakub Kozłowski
github: kubukoz/hs-learn
license: BSD3
executables:
  hs-learn-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens
    - hs-learn
description: Please see the README on GitHub at <https://github.com/kubukoz/hs-learn#readme>
